In [2]:
import cv2
import numpy as np 

height = 512
width = 512
img = np.random.randint(255, size=(height, width, 1),dtype = np.uint8)

cv2.imshow('Binary',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
v = [1,3,5,7,9]
print(v)

[1, 3, 5, 7, 9]


In [6]:
value = v[2]
print(value)

5


In [7]:
w = np.transpose(v)
print(w)

[1 3 5 7 9]


In [8]:
value = v[1:3]
print(value)

[3, 5]


In [9]:
value= v[3:]
print(value)

[7, 9]


In [11]:
value = v[::-2]
print(value)

[9, 5, 1]


In [12]:
A = [[1,4,5],
     [-5,8,9],
     [6,8,10],
     [0,2,38]]

print("A =",A)
print("A[1] =",A[1])
print("A[1][2] =", A[1][2])
print("A[0][-1] =", A[0][-1])

A = [[1, 4, 5], [-5, 8, 9], [6, 8, 10], [0, 2, 38]]
A[1] = [-5, 8, 9]
A[1][2] = 9
A[0][-1] = 5


In [16]:
A =np.array([[1,4,5],
     [-5,8,9],
     [6,8,10],
     [0,2,38]])

print("type: ", type(A))
print("A =", "\n",A,"\n")
print("A[1] =",A[1])
print("A[1][2] =", A[1][2])
print("A[0][-1] =", A[0][-1])

type:  <class 'numpy.ndarray'>
A = 
 [[ 1  4  5]
 [-5  8  9]
 [ 6  8 10]
 [ 0  2 38]] 

A[1] = [-5  8  9]
A[1][2] = 9
A[0][-1] = 5


In [18]:
C =np.array([[1,1,2], [3,5,3], [5,6,9]])
C[:,2]

array([2, 3, 9])

In [20]:
C[:,2] =1
print(C)

[[1 1 1]
 [3 5 1]
 [5 6 1]]


In [22]:
C =np.array([[1,1,2], [3,5,3], [5,6,9]])
s = sum(C[:])
print(s)
a=sum(C)
print(a)

[ 9 12 14]
[ 9 12 14]
